# src/config/tasks.yaml
tasks:
  project_planning_task:
    description: >
      Analyze the user's request: '{project_details}'. Your task is to create an
      extremely concise, high-level project plan. You MUST follow the format provided
      in the expected output EXACTLY, including the use of markdown for bolding and
      the HTML <br><br> tags for spacing. Do not add any other sections or introductory
      text.
    expected_output: >
      A super-concise, structured plan in the following markdown format:
      
      **Description:**
      - A bullet point describing the project's purpose.
      - A bullet point briefly explaining the core concept of the project.
            
      <br><br>
      
      **Process:**
      - A bullet point explaining build strategy.
      - A bullet point explaining the hardware & software selection process.
      
      <br><br>
      
      **Budget:**
      - A bullet point stating the budget.

  project_naming_task:
    description: "Create a short, catchy name (3-5 words max) for the project: {project_details}"
    expected_output: "A single string containing the short project name."

    # In src/config/tasks.yaml

  component_reasoning_task:
    description: >
      Read the project plan. Based on your internal knowledge as an expert engineer,
      create a conceptual list of components.
      
      CRITICAL INSTRUCTION: You MUST ONLY list physical, purchasable hardware components.
      Do NOT list software, libraries, firmware, algorithms, data, or any other non-physical items.
      
      Project Plan: {project_plan}
    expected_output: "A markdown table with columns: 'Sl no.', 'Component Name', 'Quantity', 'Purpose'."

  component_sourcing_task:
    description: >
      You have a table of conceptual components. For each, use your search tool to find a product on `robu.in`.
      You must produce two outputs separated by '---DATA_SEPARATOR---':
      1. A simple user-facing summary with categories and a calculated total price.
      2. A detailed markdown table with 'Sl No', 'Component Name', 'Quantity', 'Price', 'URL'.
    expected_output: "A user summary, '---DATA_SEPARATOR---', and a detailed markdown table."

  circuit_design_task:
    description: "Using the final BOM markdown table, create a Mermaid.js circuit diagram. Final BOM: {final_bom}"
    expected_output: "A code block containing the Mermaid.js diagram."

  code_generation_task:
    description: "Write a complete Arduino sketch based on the final BOM markdown table. Final BOM: {final_bom}"
    expected_output: "A code block containing the Arduino code."